ampl: reset;

ampl: option solver gurobi;

ampl: model d6.mod;

ampl: data d6.dat;

ampl: solve TEKJUR;

Gurobi 7.5.0: logical constraint _slogcon[1] is not an indicator constraint.

ampl: printf: "Lausn:\n">d6.txt;

ampl: printf{j in HLUTIR: X[j] > 0}: "Product: %s Fjoldi: %s heildartekjur: %s\n",j,X[j], v[j]*X[j]>>d6.txt;

ampl: printf: "Total weight: %s\n", sum {j in HLUTIR} X[j]*a[j]>>d6.txt;

ampl: printf: "Total volume: %s\n",sum {j in HLUTIR} X[j]*r[j]>>d6.txt;